name: Matrix Demo

# on: push
on: workflow_dispatch

jobs:
  build:
    # Unless this is set, if one job fails, the rest will be cancelled.
    continue-on-error: true
    strategy:
      matrix:
        # These keys can be anything
        node-version: [12, 14, 16]
        os: [ubuntu-latest, windows-latest]
        # This is reserved key, add single combination on top of the previous
        include:
          - node-version: 18
            os: ubuntu-latest
        exclude:
          - node-version: 12
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
