name: Reusable Deploy

on:
  workflow_call:
    inputs:
      # These keys can be anything
      artifact-name:
        description: Name of the deployable artifact
        required: true
        type: string
    secrets:
      some-secret:
        required: false
    outputs:
      result:
        description: Result of the deployment
        value: ${{ jobs.deploy.outputs.outcome }}

jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get deployment package
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying..."
      - name: Set result output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
